### ISSUE TITLE
Internal Server Error when Trying to Retrieve Tests with Invalid Ids

### ISSUE THREAD

**Issue by MO0nKe** [Noob-Software-Engineer/Bsc-Igyyan#16]
Trying to retrieve a test that does not exist.
If the supplied id is 24 characters long - 404, Document not found
If the supplied id is _**not**_ 24 characters long - 500, Internal Server error

**Comment by Ashrafkhan736** [comment]
I need to check It should through 400 error because it is not a valid object id
